version: '3.8'

networks:
  woodkunserver:
    name: woodkunserver

services:
  mysql_local:
    platform: linux/x86_64
    image: mysql:8.0.37
    container_name: mysql-woodkunserver
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - TZ=America/Araguaina
    networks:
      - woodkunserver
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 40s
      retries: 10
    command: ['mysqld', '--sql-mode=NO_ENGINE_SUBSTITUTION']